### ISSUE TITLE
Track numbers ?

### ISSUE THREAD

**Issue by notthesame23** [sk1418/zhuaxia#25]
Hi,

I'm not sure if this is already implemented. It's maybe just me not having figured it out.
When I was downloading with the neteaseMusic application, I had no problems getting track numbers importing to iTunes (iTunes does not search for info, unless you have the cd in the drive). Unfortunately with zhuaxia I don't get the track numbers right now. 
Is there a way to get this with zhuaxia ? 
Or do you have a recommendation for some other tool to get the track numbers after downloading with zhuaxia? I tried a few tools with moderate success (very often the tools confused different albums, which makes it very time consuming).

I hope you can point me in the right direction.
Thanks again for your great tool !

**Comment by sk1418** [comment]
I checked netease songs just now, I can catch the trackNo. info if there is one. I will implement it, write the trackNo. in mp3 META. at least for netease songs. 
xiami songs I haven't checked yet.

**Comment by notthesame23** [comment]
This would be fantastic. Thank you very much for the effort you are putting into this !
I just started with coding recently, so I guess I couldn't do it myself. But I will be very happy to see how something like this can be done and learn from the master.

**Comment by sk1418** [comment]
@notthesame23  the track no now is set in mp3 files downloaded from 163.  It is however **not** set for Xiami mp3 files. Because the xiami song json object returned has no trackNo info. We have to do further HTTP requests to get the trackNo. Not sure if it is worthwhile, just skip it for now.

The changes (version 3.0.1) have been pushed to master/bleeding branch. You can test.

**Comment by notthesame23** [comment]
Thank you very much for implementing this so quickly, I'm testing right now.
Unfortunately I'm having a lot of connection errors and failed tracks. I just switched to DEBUG log output to get more information about what is causing the problems. Maybe netease is just having a bad day, or probably now I will need to set a proxy server (up until now it was still working without setting a the proxy in the config file). That incremental options is really handy, when dealing with failed tracks.

**Comment by notthesame23** [comment]
Track numbers seem to work like a charm. Only tested with one album right now. I will now download a whole list of albums, and see how that goes.

**Comment by sk1418** [comment]
@notthesame23  163 probably has a kind of (not sure about the specific rule) banning rules. It will ban some IP/Session/Request when zhuaxia downloader downloads the file segments.  that's why I implemented "retry" mechanism. It could solve some connection problems. If you have been still facing those problems, as you said, change the log lvl into DEBUG and provide detailed information so that I can reproduce the problem. see if I can help.   (pls create a new issue for that)

**Comment by notthesame23** [comment]
Approx. 98 Tracks failed out of 632...not too bad in my opinion. What do you think ? If you think this could be better: I will open another thread and provide some DEBUG information tomorrow.
I'm just starting incremental download again. And after that I'll give you feedback about the track numbers, as this thread should be about this. Thanks again for your support !

**Comment by sk1418** [comment]
yep, please only report the track No result in this issue. since in commit I referenced the issue No.
I am not sure if I can solve the connection failed problem. If you could smoothly download single failed song. It could be the server side restriction. You can open a new issue. However I am not sure if I can do something to overcome this. maybe let user customize the retry times? (now hardcoded 5)

**Comment by notthesame23** [comment]
Tested new track no feature with 632 songs....working flawlessly and saves a lot of trouble when trying to order album tracks. Thank you !
